### ISSUE TITLE
Metal concentration terms CHEBI axioms

### ISSUE THREAD

**Issue by kaiiam** [UA-SRC-data/srpdio#1]
Hello @UA-SRC-data/editors  @kush-priyanka @ramonawalls and Chris Kotalik. While working to prepare the terms for the Colorado School of Mines data, I noticed there are appropriate terms which could bee taken from two main CHEBI hierarchies  [molecular entity](http://purl.obolibrary.org/obo/CHEBI_23367), and [atom](http://purl.obolibrary.org/obo/CHEBI_33250). Molecular entities are defined as `Any constitutionally or isotopically distinct atom, molecule, ion, ion pair, radical, radical ion, complex, conformer etc., identifiable as a separately distinguishable entity.` Whereas atom is defined as `A chemical entity constituting the smallest component of an element having the chemical properties of the element.`

I suspect that we’re referring to the distinguishable entities instead of the constituents with properties (as defined on the periodic table), but I could be wrong. Any thoughts based on your work doing assays to measure these elements?

I've also noticed with CHEBI that sometimes the molecular entity terms (e.g. CHEBI:[elemental cadmium](http://purl.obolibrary.org/obo/CHEBI_37249)) don't always have a molecular mass associated where as the atom terms (e.g., [cadmium atom](http://purl.obolibrary.org/obo/CHEBI_22977)) do.

Within ENVO we've made compound quality terms e.g., [solubility of carbon atom in soil](http://purl.obolibrary.org/obo/ENVO_09000002), [concentration of ammonium in liquid water](http://purl.obolibrary.org/obo/ENVO_3100004) drawing from used both hierarchies.  The latter being necessary to describe ions. Perhaps it doesn't matter for our purposes, but I'm wondering how these hierarchies are really intended for use within CHEBI. 

One clue is the axiom: `cadmium molecular entity (CHEBI:22978) has part cadmium atom (CHEBI:22977)`.

**Comment by kaiiam** [comment]
Should we maybe contact the corresponding author of the [ChEBI in 2016: Improved services and an expanding collection of metabolites paper?](https://europepmc.org/article/MED/26467479#id617772)

**Comment by ramonawalls** [comment]
Based on EnvironmentOntology/envo#946 it looks like we are converging on the molecular entity hierarchy.

**Comment by kaiiam** [comment]
@ramonawalls for now, however, see https://github.com/EnvironmentOntology/envo/issues/977, Chris might be looking to eventually move way from CHEBI to a better defined chemistry ontology (he booted up a first pass [here](https://github.com/cmungall/chemistry-ontology)). For now and this project, however, I think we'll use the CHEBI molecular entity hierarchy.

**Comment by ramonawalls** [comment]
This has been resolved.
