### ISSUE TITLE
Add licence 

### ISSUE THREAD

**Issue by kaiiam** [UA-SRC-data/srpdio#2]
@ramonawalls we should probably add a usage license, ENVO for example uses `CC0 1.0 Universal` see their [LICENSE.txt](https://github.com/EnvironmentOntology/envo/blob/master/LICENSE.txt).

**Comment by ramonawalls** [comment]
I will add CC-BY for now. We can make it open source later. @kaiiam I will make the change directly to the repo, so be sure to git pull afterwards. Shouldn't create any conflicts.

**Comment by kaiiam** [comment]
Sounds good I'll leave it up to you to decide. Let me know if you want me to add it.

**Comment by ramonawalls** [comment]
closed with commit 6ccfaf1
