### ISSUE TITLE
Creation of design pattern for named taxon plant material

### ISSUE THREAD

**Issue by kaiiam** [UA-SRC-data/srpdio#4]
As previously discussed, several UA-SRC datasets including the `Gardenroots` and `UCSD Greenhouse` datasets, as well as the harvested (crop) materials relevant to the Crop Dietary and Nutrition Ontology (see https://github.com/Southern-Cross-Plant-Science/cdno/issues/4) are chemical measurements taken from plant parts from various species, e.g. concentration of lead in Brassica oleracea shoots.  

One approach could be to use the TO:[composition](https://github.com/Planteome/plant-trait-ontology/blob/master/patterns/composition/composition.tsv) DOSDP, which crosses CHEBI terms with PO plant parts to make terms like TO:[root system lead content](http://purl.obolibrary.org/obo/TO_1000044).

However, since we also know the species information perhaps we could also include this as well in a DOSDP or Robot Template which takes PO and NCBITaxon terms as inputs (ideally together within an equivalence axiom to allow rector normalization). These `NCBITaxon cross PO` terms could then serve as input for our SRPDIO concentration terms:

```
concentration of and inheres in some (
    'CHEBI entity' and
    part of some `NCBITaxon crossed with PO Term`)
```

@ramonawalls Let me know how you want to approach this.

**Comment by ramonawalls** [comment]
For SRC, we should leave the species out of the quality class and record it as metadata for the input of the observation. This is the way the pipeline is currently set up, and we don't have resources to retool it.

**Comment by kaiiam** [comment]
@ramonawalls sounds good, as we discussed in our call I will implement this in SRPDIO by making use of the TO:composition DOSDP but change it to use PATO:`concentration of` instead of `composition`. That way we separate out the plant terms (possibly going to TO) and the chemical concentrations in environmental materials going to ENVO.

**Comment by ramonawalls** [comment]
Closing this issue for now, since we do not plan to add taxon-defined classes yet.
